### ISSUE TITLE
Why task create empty file?

### ISSUE THREAD

**Issue by makito** [JustBlackBird/gulp-xgettext#9]
Hello!
I have such a configuration:
gulp.task('generate-po', function() {
    return gulp.src('/js/*.js')
        .pipe(xgettext({
            keywords: [
                {name: 'pojs._'}
            ],
            headers: {
                Language: 'en_EN'
            }
        }))
        .pipe(concatPo('messages.po'))
        .pipe(gulp.dest('./'));
});

And in js file I have this code:
...
var someText = pojs._('Reset');
...

After run task I have file messages.po, but this file is empty.
Why?
Thanks.

**Comment by JustBlackBird** [comment]
Most likely it's because you set wrong path for source files. Look at the second line of your code:

    return gulp.src('/js/*.js')

Notice the leading slash in the path.

**Comment by JustBlackBird** [comment]
One more thing: you probably should to set `language` option to `JavaScript` like this:

```js
gulp.task('generate-po', function() {
    return gulp.src('./js/*.js')
        .pipe(xgettext({
            language: 'JavaScript',
            keywords: [
                {name: 'pojs._'}
            ],
            headers: {
                Language: 'en_EN'
            }
        }))
        .pipe(concatPo('messages.po'))
        .pipe(gulp.dest('./'));
});
```

**Comment by makito** [comment]
It is impossible, because if I remove the concatenation of all the created files on which a task runs.

**Comment by JustBlackBird** [comment]
Nevertheless once I replace a path with relative one and set language option I cannot reproduce the problem regardless of `concatPo` plugin.

Correct me if i wrong `concatPo` stands for `gulp-concat-po` plugin?

**Comment by makito** [comment]
Yes it is

**Comment by JustBlackBird** [comment]
Well, it's strange. My gulpfile is:

```js
var gulp = require('gulp'),
    concatPo = require('gulp-concat-po'),
    xgettext = require('gulp-xgettext');

gulp.task('generate-po', function() {
    return gulp.src('./js/*.js')
        .pipe(xgettext({
            language: 'JavaScript',
            keywords: [
                {name: 'pojs._'}
            ],
            headers: {
                Language: 'en_EN'
            }
        }))
        .pipe(concatPo('messages.po'))
        .pipe(gulp.dest('./'));
});
```

and contents of `./js/test.js` are:

```js
var someText = pojs._('Reset');
```

Everything works are expected.

**Comment by makito** [comment]
But if I remove concatenation plugin, i get all files for which a task runs -> task view all files, and concatenation is not to blame.

**Comment by JustBlackBird** [comment]
Are the contests of those files valid? I mean do they really .po files with extracted string or what?

**Comment by makito** [comment]
Yes it is, all generated .po files is valid, but empty

**Comment by JustBlackBird** [comment]
Ok. Does setting `language: 'JavaScript'` help?

**Comment by JustBlackBird** [comment]
It seems that the problem is already solved. I'll reopen the issue if it does not :)
